### ISSUE TITLE
Getting TypeError: s is not a function after upgrading to v5.11.0

### ISSUE THREAD

**Issue by PenghaiZhang** [swagger-api/swagger-ui#10511]
### Q&A (please complete the following information)
 - OS: Ubuntu 22
 - Browser: Chrome
 - Version: 135.0.7049.114
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 5.11.0
 - Swagger/OpenAPI version: N/A

### Content & configuration
Swagger-UI configuration options:
```js
SwaggerUI({
  dom_id: "#swagger-ui",
  url: $("base").attr("href") + "api/swagger.yaml",
});
```

### Describe the bug you're encountering
We are trying to upgrade swagger-ui from v4 to v5. It was OK when we upgraded to v5.10.5. But since v5.11.0, there is a type error occurring when we access the page.

It appears the error could be related to React, but our project is a pretty small one which does not use React in any way. We simply use webpack to generate a JS bundle file to be consumed in some html pages.

This is our webpack config.
![Image](https://github.com/user-attachments/assets/9f4ace95-10fe-4410-8841-f32ef6140092)

This is how we use the js bundle file.

![Image](https://github.com/user-attachments/assets/c4ac6c5a-4d51-431a-94e3-a95187e45b78)

### Expected behavior
The page should be correctly displayed.

### Screenshots
With 5.11.0:
![Image](https://github.com/user-attachments/assets/781c1235-1517-4f6d-8d14-32bb8082630e)

With 5.10.5:

![Image](https://github.com/user-attachments/assets/8ec73d5d-1b9b-4def-ac46-c1df4b5ee7d4)

**Comment by glowcloud** [comment]
Hi @PenghaiZhang ,

I could not reproduce this issue on my end. Could you check if it still occurs for you with the latest release of Swagger UI? From the stack trace, it looks like the error might be related to the `downloadSpec` function, which was rewritten and merged into another function. These changes might have resolved your issue.

**Comment by PenghaiZhang** [comment]
> Hi [@PenghaiZhang](https://github.com/PenghaiZhang) ,
> 
> I could not reproduce this issue on my end. Could you check if it still occurs for you with the latest release of Swagger UI? From the stack trace, it looks like the error might be related to the `downloadSpec` function, which was rewritten and merged into another function. These changes might have resolved your issue.

Hi @glowcloud we have tried 5.25.x and 5.26.2, and still have this error.  Could this be related to Webpack ?

**Comment by PenghaiZhang** [comment]
So looks like `s` refers to  the `React.createRoot` function which becomes undefined for some reasons.

**Comment by PenghaiZhang** [comment]
I just found that maybe the version of react is wrong.  I think it should be v18 but what I have is v17.

**Comment by PenghaiZhang** [comment]
I added `react` and `react-dom` in my package.json although I do not need these two deps, and then the page kind of worked with this warning:

> react-dom.development.js:86 Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

Also the text in the page seems broken - texts are displayed vertically.

<img width="2005" height="760" alt="Image" src="https://github.com/user-attachments/assets/3f43301a-8b12-4b76-8902-2ca4b238e74a" />

**Comment by glowcloud** [comment]
Could there be an issue with the CSS load order?

I also uploaded a [project](https://github.com/glowcloud/swagger-ui-webpack) based on most of the configuration provided here, if you would like to check if you have any problems there as well. There was no need for the additional `react` or `react-dom` dependencies to make it work. Perhaps completely regenerating `package-lock` and `node_modules` would help?

**Comment by lowkeycode** [comment]
fwiw Hitting this in an Angular 2 project as well moving from 14.19.1 to 5.28.0. Regenerating the package-lock and node_modules had no effect

**Comment by sunio00000** [comment]
i got same issue in 5.28.1

OS: Win 11
Browser: Chrome
Version: 140.0.7339.80
Method of installation: pnpm
Swagger-UI version: 5.28.1
Swagger/OpenAPI version: 3.0.1

<img width="402" height="263" alt="Image" src="https://github.com/user-attachments/assets/a1044f11-5093-4789-b848-b4dba8574f3e" />
