### ISSUE TITLE
OAS3 TypeError: i is not a function, 3.3.0

### ISSUE THREAD

**Issue by denisprsa** [swagger-api/swagger-ui#3718]
Hey, I just tried new version of swagger ui 3.3.0 ui on openapi 3.0.0. 
When i try to click on path I I get following error.

<img width="1433" alt="screen shot 2017-09-30 at 17 29 20" src="https://user-images.githubusercontent.com/10304660/31047209-9c4cc304-a606-11e7-8b51-cb21259199d5.png">

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?   | 3.0.0
| Which Swagger-UI version?       | 3.3.0
| How did you install Swagger-UI? | dist folder
| Which browser & version?        | Chrome, 61.0.3163.100
| Which operating system?         | macOS

**Comment by shockey** [comment]
Hey @denisprsa, thanks for the report.

I'm only able to reproduce this under certain circumstances, can you see below and confirm that you're experiencing the same?

- **Can** reproduce by opening Swagger-UI, pasting an OpenAPI 3 definition URL into the Topbar, and clicking Explore. 
  - The display does not update - the previous definition's content stays on the screen.
  - Clicking Explore a second time solves the issue.
- **Can't** reproduce this by opening the same definition directly through configuration
  - Example: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uber.yaml

It appears that something in the ModelExample code is failing, which is making the render fail:

> Uncaught TypeError: getConfigs is not a function
>    at new ModelExample (model-example.jsx:58)
>     at eval (ReactCompositeComponent.js:292)

This was probably introduced in #3628. It's worth noting that ModelExample failing should not cause the entire application to bail out of a render cycle, that needs to be investigated as well.

---

Please confirm that the workaround I mentioned works for you. If it does, I'd like to mark this as high priority so we get to it next week. OTOH, if you're completely unable to open an OpenAPI 3.0 definition, that is _bad_ and we'll get a patch out this weekend.

Thanks!

**Comment by ssimplix** [comment]
Same for me. The problem seems related to `requestBody` field - when I remove it, everything works.

YAML:

````yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /users:
    post:
      tags:
      - pet
      summary: Updates a pet in the store with form data
      operationId: updatePetWithForm
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
             properties:
                name:
                  description: Updated name of the pet
                  type: string
                status:
                  description: Updated status of the pet
                  type: string
             required:
               - status
      responses:
        '200':
          description: Pet updated.
````

Version 60.0.3112.113 (Official Build) (64-bit), OAS 3.0.0, Swagger UI v3.0.0. I run Swagger UI via dist folder.

**Comment by ErikJansenIRefact** [comment]
When modelExample is rendered getConfigs is not available. It is not passed in the props so getConfigs() is undefined and results in an error. It seems to happen if a reference to schema component is created in path operations and parameters.

**Comment by dmitriiivashko** [comment]
same issue here: JS error when `requestBody` is defined for a path method object

**Comment by shockey** [comment]
Hi everyone, I'm going to publish this fix in a patch version (`swagger-ui@3.3.1`). It should be available in the online UI at http://petstore.swagger.io, as well as on NPM, within the hour.

Sorry for the inconvenience!

**Comment by gest80** [comment]
I got a similar error, when a request with required field is send without value.
YAML:
`
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
servers:
  - url: http://petstore.swagger.io/api
paths:
  /pets/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: find pet by id
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64

    NewPet:
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string    

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
`
Tested with version 3.3.1

![js_error](https://user-images.githubusercontent.com/11681524/31431403-e06090fa-ae73-11e7-90c5-4a7fd006bd15.png)
