### ISSUE TITLE
Version 4.10.3 causes next.js app to fail run due to a SyntaxError

### ISSUE THREAD

**Issue by simPod** [swagger-api/swagger-ui#7970]
Similar to https://github.com/swagger-api/swagger-ui/issues/7944 but for next.js

### Q&A (please complete the following information)
 - OS: macos/linux
 - Method of installation: npm
 - Swagger-UI version: 4.10.3

### Content & configuration

```
{
  "compilerOptions": {
    "target": "ES6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
```

### Describe the bug you're encountering

In next.js app build crashes on 

```
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/path/node_modules/swagger-ui-react/commonjs.js:10:53)
    at Module._compile (node:internal/modules/cjs/loader:1099:14) {
  type: 'SyntaxError'
}
```

### To reproduce...

- Require swagger react 
- `import SwaggerUI from 'swagger-ui-react';`

### Expected behavior
No err

### Additional context or thoughts

It worked ok on 4.2.1

**Comment by motechFR** [comment]
I've also run into this issue with Next.js

Workaround for now is to downgrade to swagger-ui-react 4.6.1

**Comment by mustaphaturhan** [comment]
I've also run into same issue with Next.js@12.1.4.

I though downgrading swagger-ui-react to 4.8.1 can solve this problem but it was breaking my application after build. It was showing an error in UI `Application error: a client-side exception has occurred (see the browser console for more information).` and `TypeError: batch is not a function` in console.

This error is happening if you are using new [swc minifier](https://nextjs.org/docs/advanced-features/compiler#minification). I removed `swcMinify: true` from my `next.config.js` file as a workaround.

**Comment by TannicArturo98** [comment]
I'm using Next.js@11.0.1 and it got only with swagger-ui-react v4.9.0 and above this error.

Using v4.8.1 it builds without errors but, when i try to build for production on Vercel, it returns me the same error:
![image](https://user-images.githubusercontent.com/53819131/162141762-be3c2a62-dff2-4ed3-9d1b-ce1936d3e079.png)

**Comment by Xhale1** [comment]
Can confirm that this error exist for v4.9.0 and up on a fresh next.js installation.

**Comment by DjVreditel** [comment]
It worked for me:

```JS
import dynamic from "next/dynamic";

const SwaggerUI = dynamic(import('swagger-ui-react'), {ssr: false})

const Test = () => <SwaggerUI spec={data}/>
export default Test
```

**Comment by TannicArturo98** [comment]
> 

It works.

**Comment by rafinskipg** [comment]
typescript will complain about spec not being a recognized property on swaggerUI with the dynamic import

**Comment by rbong** [comment]
Just in case anyone runs into the same issue - I tried the dynamic import solution, but still ran into the error transpiling while using `babel-plugin-istanbul`. @char0n 's solution using transpilation instead fixed it for me.

**Comment by char0n** [comment]
Created a [POC repo](https://github.com/char0n/swagger-ui-nextjs) integrating `swagger-ui-react@5` with `next@13.4.9`. Looks like Next.js now work with SwaggerUI without any configuration. This is probably related to https://github.com/swagger-api/swagger-ui/commit/6aa1b445b96cd9e26646b51ea99a54d86e6d59f1

**Comment by char0n** [comment]
Created a SwaggerUI wiki page https://github.com/swagger-api/swagger-ui/wiki/Seamless-Integration-with-Bundlers-&-Test-Tools where integration with Next.js is now documented.
