### PR TITLE
fix: Import createRoot from react-dom/client

### LINKED ISSUE #10511: Getting TypeError: s is not a function after upgrading to v5.11.0
### Q&A (please complete the following information)
 - OS: Ubuntu 22
 - Browser: Chrome
 - Version: 135.0.7049.114
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 5.11.0
 - Swagger/OpenAPI version: N/A

### Content & configuration
Swagger-UI configuration options:
```js
SwaggerUI({
  dom_id: "#swagger-ui",
  url: $("base").attr("href") + "api/swagger.yaml",
});
```

### Describe the bug you're encountering
We are trying to upgrade swagger-ui from v4 to v5. It was OK when we upgraded to v5.10.5. But since v5.11.0, there is a type error occurring when we access the page.

It appears the error could be related to React, but our project is a pretty small one which does not use React in any way. We simply use webpack to generate a JS bundle file to be consumed in some html pages.

This is our webpack config.
Image

This is how we use the js bundle file.

Image

### Expected behavior
The page should be correctly displayed.

### Screenshots
With 5.11.0:
Image

With 5.10.5:

Image

### LINKED ISSUE #10636: new SwaggerUI(...) fails with "s is not a function" error after upgrading to swagger-ui@5.28.0
### Q&A (please complete the following information)
 - OS: Ubuntu 22.04
 - Browser:  chrome
 - Version:  142.0
 - Method of installation:  npm
 - Swagger-UI version:  5.28.0
 - Swagger/OpenAPI version: Swagger 1.0, OpenAPI 2.0

### Content & configuration
Here's a sandbox with a minimal reproduction using swagger-ui v5.27.1 which works as expected
https://codesandbox.io/p/devbox/swagger-ui-5-27-1-example-forked-cwkfst?workspaceId=ws_7URHuAnb4he8p4EieYcckW

### Describe the bug you're encountering

And this is a copy of the above sandbox that only changes swagger-ui in package.json to v5.28.0
https://codesandbox.io/p/sandbox/eager-bessie-2mvrk4

and now I get an error instead of swagger-ui rendered 
```
TypeError
s is not a function
Object.eval [as render]
/node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js:2:228223
```

### To reproduce...

1. Just open my reproduction: https://codesandbox.io/p/sandbox/eager-bessie-2mvrk4

### Expected behavior

swagger-ui v5.28.0 works the same as v5.27.1

### Screenshots

Sandbox with swagger-ui v5.27.1

Image

Sandbox with swagger-ui v5.28.0

Image

### PR DESCRIPTION
**Pull request by berkhoutalex**
### Description

Switches the createRoot import from react-dom to react-dom/client

### Motivation and Context

In React 18.0, render was deprecated and replaced by ReactDOMClient.createRoot, but they also had createRoot in just ReactDOM. In React 19.0, they removed ReactDOM.createRoot, which is causing errors with swagger that look like 's is not a function'. When running swagger with React 18.3, it shows this warning "Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client"." and then react 19.0 crashes
image
https://react.dev/blog/2024/04/25/react-19-upgrade-guide

Fixes #10511 
Fixes #10636 

### How Has This Been Tested?
Ran the dev server on master with React pinned to 19, and I got 
image
Then on this branch, running the dev server on every working react version (18, 19. The current dependencies do not let you install react earlier than 18) rendered with no isssues

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by akostadinov** [comment]
Bump, any maintainer wants to look at this? :angel:

**Comment by alorence** [comment]
Please... This issue is open for a year now, the fix is only a 2-lines change...

🙏🏼

**Comment by gerinjacob** [comment]
Can the maintainers prioritise this PR?
